### ISSUE TITLE
公网访问时报错

### ISSUE THREAD

**Issue by nameless147** [velor2012/anonymous-chat-room#2]
localhost访问可以正常使用，公网访问会报错，请问是哪里部署有问题？
![HBLE0FBI8OGE)KSL01~@5D1](https://github.com/velor2012/anonymous-chat-room/assets/139883069/1dfa682a-a28f-4648-986a-7fa474fc2da5)

**Comment by velor2012** [comment]
error那一行红字已经说了，需要开启ssl，使用https访问

**Comment by nameless147** [comment]
> error那一行红字已经说了，需要开启ssl，使用https访问

谢谢，后面发现了所以自己关闭了。
