### ISSUE TITLE
这个报错是啥 

### ISSUE THREAD

**Issue by jackc4bug** [velor2012/anonymous-chat-room#3]
![image](https://github.com/velor2012/anonymous-chat-room/assets/133853723/6f6234a4-a71e-4135-9bdf-899f44c76da0)

**Comment by jackc4bug** [comment]
我该如何去解决这个报错

**Comment by velor2012** [comment]
您好，请描述一下复现的步骤

**Comment by jackc4bug** [comment]
> 您好，请描述一下复现的步骤

拉下代码，修改配置文件，启动，进入主页报错。

**Comment by velor2012** [comment]
我这边直接使用example的配置似乎没什么问题，您可以发配置给我测试一下吗，2281675608@qq.com
