### ISSUE TITLE
我知道这很蠢，但是我希望如何以https的方式部署

### ISSUE THREAD

**Issue by AIRBUS-A350-1000XWB** [velor2012/anonymous-chat-room#5]

**Comment by velor2012** [comment]
你好，一般来说如果部署在vercel等paas服务商的话他们会自己搞定https的。如果需要自己部署，推荐使用nginx进行反向代理，交给nginx完成https，实在不会的话使用宝塔等工具即可

**Comment by AIRBUS-A350-1000XWB** [comment]
> 你好，一般来说如果部署在vercel等paas服务商的话他们会自己搞定https的。如果需要自己部署，推荐使用nginx进行反向代理，交给nginx完成https，实在不会的话使用宝塔等工具即可

👌谢谢，用nginx解决嘞
